CREATE TABLE ARTIST(
	[ARTIST_NAME] [nvarchar](255) NOT NULL,
	[ARTIST_ID] [nvarchar](50) NOT NULL,
	[HREF] [nvarchar](max) NULL,
	[POPULARITY] [int] NULL,
	[URI] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)