CREATE TABLE PLAYLIST_TRACK(
	[PLAYLIST_ID] [nvarchar](50) NOT NULL,
	[TRACK_ID] [nvarchar](50) NOT NULL,
	[IS_LOCAL] [nchar](10) NULL,
	[ADDED_AT] [datetime] NULL,
	[ADDED_BY] [nvarchar](50) NULL,
 CONSTRAINT [PK_PLAYTRACK] PRIMARY KEY CLUSTERED 
(
	[PLAYLIST_ID] ASC,
	[TRACK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)